import { StyleSheet } from "react-native";
import { T, FONT } from "../constants/typography";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent', // Let background map show
  },
  scrollContent: {
    paddingBottom: 40,
    minHeight: '100%',
  },
  header: {
    alignItems: 'center',
    padding: 20,
    paddingTop: 65,
    position: 'relative',
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    marginBottom: 20,
  },
  backButton: {
    position: 'absolute',
    left: 20,
    top: 65,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  title: {
    ...T.title3,
    fontSize: 20,
    marginTop: 4,
    maxWidth: "70%",
    textAlign: "center",
    marginBottom: 6,
  },
  subtitle: {
    ...T.bodyMuted,
    fontSize: 13,
    marginBottom: 10,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    marginHorizontal: 20,
    marginBottom: 10,
    borderRadius: 16,
    padding: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  tab: {
    flex: 1,
    padding: 12,
    alignItems: 'center',
    borderRadius: 12,
  },
  activeTab: {
    backgroundColor: '#24C789',
    shadowColor: '#24C789',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  tabText: {
    fontFamily: FONT.bold,
    fontSize: 14,
    color: '#888888',
    letterSpacing: 0.2,
  },
  activeTabText: {
    fontFamily: FONT.extraBold,
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  tabContent: {
    padding: 20,
    paddingTop: 10,
  },
  friendsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    ...T.title2,
    fontSize: 22,
  },
  addButton: {
    backgroundColor: '#24C789',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 24,
    shadowColor: '#24C789',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  addButtonText: {
    ...T.button,
    fontSize: 13,
  },
  addFriendContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 24,
    borderRadius: 24,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
  },
  input: {
    backgroundColor: '#F4F5F7',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    fontFamily: FONT.semibold,
    fontSize: 15,
    color: '#222222',
    borderWidth: 1,
    borderColor: '#EAEAEA',
  },
  confirmButton: {
    backgroundColor: '#24C789',
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#24C789',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  confirmButtonText: {
    ...T.button,
    letterSpacing: 1,
  },
  friendCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 20,
    borderRadius: 24,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  friendInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  friendMain: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
  },
  friendAvatar: {
    fontSize: 44,
    marginRight: 16,
    backgroundColor: '#F4F5F7',
    borderRadius: 24,
    padding: 8,
    overflow: 'hidden',
  },
  friendAvatarImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 16,
  },
  friendDetails: {
    flex: 1,
  },
  friendName: {
    ...T.title3,
    fontSize: 18,
    marginBottom: 4,
  },
  friendStats: {
    fontFamily: FONT.semibold,
    fontSize: 13,
    color: '#888888',
    marginBottom: 4,
  },
  friendLastRun: {
    ...T.caption,
    color: '#999999',
  },
  friendStatus: {
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  statusIndicator: {
    ...T.pill,
    color: '#999999',
    backgroundColor: '#F4F5F7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    overflow: 'hidden',
  },
  online: {
    color: '#24C789',
    backgroundColor: 'rgba(36, 199, 137, 0.1)',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 24,
    marginTop: 20,
  },
  emptyText: {
    ...T.title3,
    marginBottom: 8,
  },
  emptySubtext: {
    ...T.bodyMuted,
    fontSize: 15,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 17, 17, 0.6)',
    justifyContent: 'flex-end',
  },
  profileSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  sheetHandle: {
    width: 48,
    height: 6,
    backgroundColor: '#EAEAEA',
    borderRadius: 3,
    marginBottom: 24,
  },
  sheetHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  sheetAvatar: {
    fontSize: 64,
    marginBottom: 16,
    backgroundColor: '#F4F5F7',
    padding: 16,
    borderRadius: 48,
    overflow: 'hidden',
  },
  sheetName: {
    ...T.title2,
    fontSize: 22,
    marginTop: 4,
    maxWidth: "70%",
    textAlign: "center",
    marginBottom: 4,
  },
  sheetPhone: {
    fontFamily: FONT.semibold,
    fontSize: 15,
    color: '#888888',
  },
  sheetStats: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 30,
    marginBottom: 30,
    width: '100%',
    paddingVertical: 20,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F4F5F7',
  },
  sheetStatBox: {
    alignItems: 'center',
  },
  sheetStatVal: {
    ...T.metricL,
    fontSize: 24,
    color: '#24C789',
    marginBottom: 4,
  },
  sheetStatLbl: {
    ...T.label,
    fontSize: 11,
  },
  cheerQuickBtn: {
    backgroundColor: '#F4F5F7',
    padding: 16,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    width: 70,
    height: 70,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  chatBtn: {
    backgroundColor: '#24C789',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 20,
    width: '100%',
    marginBottom: 16,
    shadowColor: '#24C789',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  chatBtnText: {
    ...T.button,
    fontSize: 17,
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  removeFriendBtn: {
    padding: 16,
    width: '100%',
    alignItems: 'center',
  },
  removeFriendBtnText: {
    fontFamily: FONT.bold,
    color: '#FF3B30',
    fontSize: 15,
  },


  // FEED STYLES
  feedCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  feedAvatarImg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 12,
  },
  feedAvatarEmoji: {
    fontSize: 32,
    width: 44,
    height: 44,
    textAlign: 'center',
    lineHeight: 44,
    backgroundColor: '#F4F5F7',
    borderRadius: 22,
    marginRight: 12,
    overflow: 'hidden',
  },
  feedHeaderInfo: {
    flex: 1,
  },
  feedName: {
    fontFamily: FONT.extraBold,
    fontSize: 15,
    color: '#222',
    letterSpacing: -0.2,
  },
  feedTime: {
    ...T.caption,
    marginTop: 2,
  },
  feedMapPlaceholder: {
    height: 140,
    backgroundColor: '#F4F5F7',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  feedMapText: {
    color: '#888',
    marginTop: 8,
    fontWeight: '600',
  },
  feedStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F0F0F0',
  },
  feedStatBox: {
    alignItems: 'center',
  },
  feedStatVal: {
    ...T.metricM,
    fontSize: 18,
  },
  feedStatLabel: {
    ...T.caption,
    fontSize: 11,
  },
  feedActions: {
    flexDirection: 'row',
    gap: 20,
  },
  feedActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  feedActionText: {
    fontFamily: FONT.semibold,
    fontSize: 13,
    marginLeft: 6,
    color: '#666',
  },

  // LEADERBOARD STYLES
  leaderboardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 16,
    borderRadius: 20,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  rankContainer: {
    width: 40,
    alignItems: 'center',
  },
  rank: {
    ...T.metricM,
    fontSize: 18,
    color: '#24C789',
  },
  leaderAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  leaderAvatar: {
    fontSize: 32,
    width: 44,
    height: 44,
    textAlign: 'center',
    lineHeight: 44,
    backgroundColor: '#F4F5F7',
    borderRadius: 22,
    marginRight: 12,
    overflow: 'hidden',
  },
  leaderInfo: {
    flex: 1,
  },
  leaderName: {
    fontFamily: FONT.extraBold,
    fontSize: 15,
    color: '#222',
    letterSpacing: -0.2,
  },
  leaderDistance: {
    fontFamily: FONT.semibold,
    fontSize: 13,
    color: '#888',
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  medal: {
      fontSize: 24,
    },

  feedCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  feedAvatarImg: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F0F0F0',
  },
  feedAvatarEmoji: {
    fontSize: 32,
    marginRight: 10,
  },
  feedHeaderInfo: {
    marginLeft: 12,
    flex: 1,
  },
  feedName: {
    fontFamily: FONT.extraBold,
    fontSize: 16,
    color: '#222',
    letterSpacing: -0.2,
  },
  feedTime: {
    ...T.caption,
    fontSize: 13,
    marginTop: 2,
  },
  feedMapPlaceholder: {
    height: 160,
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  feedMapText: {
    fontFamily: FONT.semibold,
    marginTop: 8,
    color: '#999',
    fontSize: 13,
  },
  feedStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#F8F9FA',
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
  },
  feedStatBox: {
    alignItems: 'center',
  },
  feedStatVal: {
    ...T.metricL,
    fontSize: 20,
  },
  feedStatLabel: {
    ...T.label,
    fontSize: 11,
    marginTop: 4,
  },
  feedActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
    paddingTop: 16,
    paddingHorizontal: 10,
  },
  feedActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
  },
  feedActionText: {
    fontFamily: FONT.bold,
    fontSize: 13,
    color: '#555',
    marginLeft: 8,
  },
  emptyFeedState: {
    alignItems: 'center',
    marginTop: 60,
    padding: 20,
  },
  emptyFeedText: {
    fontFamily: FONT.bold,
    fontSize: 17,
    color: '#888',
    marginTop: 16,
    letterSpacing: -0.2,
  },
});
