import { StyleSheet, Platform } from "react-native";
import { T, FONT } from "../constants/typography";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F5F7",
  },
  scrollContent: {
    paddingBottom: 40,
    minHeight: "100%",
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 56 : 36,
    paddingBottom: 20,
    backgroundColor: "#FFFFFF",
    marginBottom: 12,
  },
  headerTopRow: {
    height: 44,
    justifyContent: "center",
    marginBottom: 4,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F4F5F7",
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    ...T.title1,
    fontSize: 28,
    textAlign: "left",
    marginBottom: 4,
  },
  subtitle: {
    ...T.bodyMuted,
    fontSize: 14,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    marginHorizontal: 20,
    marginBottom: 12,
    borderRadius: 14,
    padding: 4,
    shadowColor: "#0B0F13",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 10,
  },
  activeTab: {
    backgroundColor: "#0B0F13",
  },
  tabText: {
    fontFamily: FONT.bold,
    fontSize: 13,
    color: "#6B6F76",
    letterSpacing: 0.2,
  },
  activeTabText: {
    fontFamily: FONT.extraBold,
    color: "#FFFFFF",
    letterSpacing: 0.2,
  },
  tabContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  friendsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    ...T.title3,
    fontSize: 18,
    marginBottom: 12,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0B0F13",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  addButtonText: {
    ...T.button,
    fontSize: 12,
    letterSpacing: 0.3,
  },
  addFriendContainer: {
    backgroundColor: "#FFFFFF",
    padding: 20,
    borderRadius: 20,
    marginBottom: 16,
    shadowColor: "#0B0F13",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 3,
  },
  input: {
    backgroundColor: "#F4F5F7",
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 48,
    marginBottom: 12,
    fontFamily: FONT.semibold,
    fontSize: 14,
    color: "#0B0F13",
  },
  confirmButton: {
    backgroundColor: "#0B0F13",
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmButtonText: {
    ...T.button,
    fontSize: 14,
    letterSpacing: 0.3,
  },
  friendCard: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: 20,
    marginBottom: 12,
    shadowColor: "#0B0F13",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  friendInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  friendMain: {
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
  },
  friendAvatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 14,
  },
  friendAvatarFallback: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F4F5F7",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  friendAvatarInitial: {
    fontFamily: FONT.extraBold,
    fontSize: 17,
    color: "#0B0F13",
    letterSpacing: -0.3,
  },
  friendDetails: {
    flex: 1,
  },
  friendName: {
    ...T.title4,
    fontSize: 16,
    marginBottom: 2,
  },
  friendStats: {
    fontFamily: FONT.medium,
    fontSize: 12,
    color: "#6B6F76",
    marginBottom: 2,
    fontVariant: ["tabular-nums"],
  },
  friendLastRun: {
    ...T.caption,
    fontSize: 11,
    color: "#9AA0A6",
  },
  friendStatus: {
    alignItems: "flex-end",
    justifyContent: "center",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#C9CCD1",
    marginRight: 6,
  },
  statusDotOnline: {
    backgroundColor: "#24C789",
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F4F5F7",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  statusPillText: {
    fontFamily: FONT.bold,
    fontSize: 10,
    letterSpacing: 0.8,
    color: "#6B6F76",
    textTransform: "uppercase",
  },
  statusPillTextOnline: {
    color: "#1A9D6C",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(11, 15, 19, 0.55)",
    justifyContent: "flex-end",
  },
  profileSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 32,
    alignItems: "center",
    shadowColor: "#0B0F13",
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#E4E6EA",
    borderRadius: 2,
    marginBottom: 18,
  },
  sheetHeader: {
    alignItems: "center",
    marginBottom: 20,
    alignSelf: "stretch",
    position: "relative",
  },
  sheetAvatarFallback: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#F4F5F7",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  sheetAvatarInitial: {
    fontFamily: FONT.extraBold,
    fontSize: 28,
    color: "#0B0F13",
    letterSpacing: -0.5,
  },
  sheetAvatarImage: {
    width: 72,
    height: 72,
    borderRadius: 36,
    marginBottom: 14,
  },
  sheetClose: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F4F5F7",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetName: {
    ...T.title2,
    fontSize: 22,
    textAlign: "center",
    marginBottom: 2,
  },
  sheetPhone: {
    fontFamily: FONT.medium,
    fontSize: 13,
    color: "#6B6F76",
  },
  sheetStats: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 36,
    marginBottom: 24,
    width: "100%",
    paddingVertical: 18,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#F4F5F7",
  },
  sheetStatBox: {
    alignItems: "center",
  },
  sheetStatVal: {
    ...T.metricL,
    fontSize: 22,
    marginBottom: 4,
  },
  sheetStatLbl: {
    ...T.label,
    fontSize: 10,
  },
  chatBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0B0F13",
    height: 52,
    borderRadius: 26,
    width: "100%",
    marginBottom: 10,
    shadowColor: "#0B0F13",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 4,
  },
  chatBtnSecondary: {
    backgroundColor: "#FF5A36",
    shadowColor: "#FF5A36",
  },
  chatBtnText: {
    ...T.button,
    fontSize: 15,
    marginLeft: 8,
    letterSpacing: 0.3,
  },
  removeFriendBtn: {
    paddingVertical: 14,
    width: "100%",
    alignItems: "center",
  },
  removeFriendBtnText: {
    fontFamily: FONT.bold,
    color: "#FF5A36",
    fontSize: 14,
    letterSpacing: 0.3,
  },

  // FEED STYLES
  feedCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
    shadowColor: "#0B0F13",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  feedHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  feedAvatarImg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  feedAvatarFallback: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F4F5F7",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  feedAvatarInitial: {
    fontFamily: FONT.extraBold,
    fontSize: 15,
    color: "#0B0F13",
  },
  feedHeaderInfo: {
    flex: 1,
  },
  feedName: {
    ...T.title4,
    fontSize: 15,
    color: "#0B0F13",
  },
  feedTime: {
    ...T.caption,
    fontSize: 12,
    marginTop: 2,
  },
  feedMapPlaceholder: {
    height: 140,
    backgroundColor: "#F4F5F7",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  feedMapText: {
    fontFamily: FONT.semibold,
    fontSize: 12,
    color: "#6B6F76",
    marginTop: 6,
  },
  feedStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#F4F5F7",
    marginBottom: 12,
  },
  feedStatBox: {
    alignItems: "center",
  },
  feedStatVal: {
    ...T.metricM,
    fontSize: 16,
  },
  feedStatLabel: {
    ...T.label,
    fontSize: 10,
    marginTop: 2,
  },
  feedActions: {
    flexDirection: "row",
    gap: 18,
  },
  feedActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
  },
  feedActionText: {
    fontFamily: FONT.semibold,
    fontSize: 13,
    marginLeft: 5,
    color: "#6B6F76",
  },
  emptyFeedState: {
    alignItems: "center",
    marginTop: 40,
    padding: 20,
  },
  emptyFeedText: {
    ...T.title3,
    fontSize: 17,
    color: "#9AA0A6",
    marginTop: 12,
  },

  // LEADERBOARD STYLES
  leaderboardItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginBottom: 10,
    shadowColor: "#0B0F13",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  rankContainer: {
    width: 28,
    alignItems: "center",
    marginRight: 8,
  },
  rank: {
    fontFamily: FONT.extraBold,
    fontSize: 16,
    color: "#9AA0A6",
    letterSpacing: -0.3,
    fontVariant: ["tabular-nums"],
  },
  leaderAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  leaderAvatarFallback: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F4F5F7",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  leaderAvatarInitial: {
    fontFamily: FONT.extraBold,
    fontSize: 15,
    color: "#0B0F13",
  },
  leaderInfo: {
    flex: 1,
  },
  leaderName: {
    fontFamily: FONT.extraBold,
    fontSize: 15,
    color: "#0B0F13",
    letterSpacing: -0.2,
  },
  leaderDistance: {
    fontFamily: FONT.medium,
    fontSize: 12,
    color: "#6B6F76",
    marginTop: 2,
    fontVariant: ["tabular-nums"],
  },
  medalBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
});
