import { StyleSheet } from "react-native";

export default 
StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F5F7',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 20,
    top: 60,
    zIndex: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: '#111111',
    marginBottom: 8,
    letterSpacing: -0.5,
    textTransform: 'uppercase',
  },
  subtitle: {
    fontSize: 16,
    color: '#888888',
    marginBottom: 10,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    margin: 20,
    marginTop: 0,
    borderRadius: 12,
    padding: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  tab: {
    flex: 1,
    padding: 14,
    alignItems: 'center',
    borderRadius: 8,
  },
  activeTab: {
    backgroundColor: '#24C789',
  },
  tabText: {
    fontSize: 16,
    color: '#888888',
    fontWeight: '600',
  },
  activeTabText: {
    color: '#FFFFFF',
  },
  tabContent: {
    padding: 20,
    paddingTop: 0,
  },
  friendsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#222222',
  },
  addButton: {
    backgroundColor: '#24C789',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  addFriendContainer: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  input: {
    backgroundColor: '#F4F5F7',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    fontSize: 16,
    color: '#222222',
  },
  confirmButton: {
    backgroundColor: '#24C789',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  confirmButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 1,
  },
  friendCard: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  friendInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  friendMain: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
  },
  friendAvatar: {
    fontSize: 40,
    marginRight: 16,
  },
  friendAvatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 16,
  },
  friendDetails: {
    flex: 1,
  },
  friendName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222222',
    marginBottom: 4,
  },
  friendStats: {
    fontSize: 14,
    color: '#888888',
    marginBottom: 4,
    fontWeight: '500',
  },
  friendLastRun: {
    fontSize: 12,
    color: '#999999',
  },
  friendStatus: {
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  statusIndicator: {
    fontSize: 12,
    fontWeight: '700',
    color: '#999999',
  },
  online: {
    color: '#24C789',
  },
  friendActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  cheerButton: {
    backgroundColor: '#F0F0F0',
    paddingVertical: 12,
    borderRadius: 12,
    flex: 2,
    alignItems: 'center',
  },
  cheerButtonText: {
    color: '#444444',
    fontWeight: 'bold',
    fontSize: 15,
  },
  removeButton: {
    backgroundColor: '#FFEBEE',
    paddingVertical: 12,
    borderRadius: 12,
    flex: 1,
    alignItems: 'center',
  },
  removeButtonText: {
    color: '#FF453A',
    fontWeight: 'bold',
    fontSize: 15,
  },
  emptyState: {
    alignItems: 'center',
    padding: 60,
  },
  emptyText: {
    fontSize: 20,
    color: '#222222',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  emptySubtext: {
    fontSize: 15,
    color: '#888888',
    textAlign: 'center',
    lineHeight: 22,
  },
  leaderboardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  rankContainer: {
    width: 40,
    alignItems: 'center',
  },
  rank: {
    fontSize: 18,
    fontWeight: '900',
    color: '#999999',
  },
  leaderAvatar: {
    fontSize: 32,
    marginRight: 16,
  },
  leaderAvatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 16,
  },
  leaderInfo: {
    flex: 1,
  },
  leaderName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222222',
  },
  leaderDistance: {
    fontSize: 15,
    color: '#24C789',
    fontWeight: '600',
    marginTop: 4,
  },
  medal: {
    fontSize: 28,
  },
  feedCard: {
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  feedAvatarEmoji: {
    fontSize: 32,
    marginRight: 10,
  },
  feedAvatarImg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  feedHeaderInfo: {
    flex: 1,
  },
  feedName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
  },
  feedTime: {
    fontSize: 12,
    color: '#888',
  },
  feedMapPlaceholder: {
    width: '100%',
    height: 150,
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  feedMapText: {
    fontSize: 14,
    color: '#AAA',
    marginTop: 8,
  },
  feedStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F0F0F0',
  },
  feedStatBox: {
    alignItems: 'center',
  },
  feedStatVal: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222',
  },
  feedStatLabel: {
    fontSize: 12,
    color: '#888',
  },
  feedActions: {
    flexDirection: 'row',
  },
  feedActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 24,
  },
  feedActionText: {
    marginLeft: 6,
    color: '#666',
    fontWeight: '500',
  },
  feedCard: {
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  feedAvatarEmoji: {
    fontSize: 32,
    marginRight: 10,
  },
  feedAvatarImg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  feedHeaderInfo: {
    flex: 1,
  },
  feedName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
  },
  feedTime: {
    fontSize: 12,
    color: '#888',
  },
  feedMapPlaceholder: {
    width: '100%',
    height: 150,
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  feedMapText: {
    fontSize: 14,
    color: '#AAA',
    marginTop: 8,
  },
  feedStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#F0F0F0',
  },
  feedStatBox: {
    alignItems: 'center',
  },
  feedStatVal: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222',
  },
  feedStatLabel: {
    fontSize: 12,
    color: '#888',
  },
  feedActions: {
    flexDirection: 'row',
  },
  feedActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 24,
  },
  feedActionText: {
    marginLeft: 6,
    color: '#666',
    fontWeight: '500',
  },
});
