import { StyleSheet, Dimensions, Platform } from 'react-native';

const { height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000', // Dark premium mode
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F4F5F7',
  },
  loadingText: {
    fontSize: 16,
    color: '#888',
    fontWeight: '500',
  },
  mapContainer: {
    height: height * 0.55,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : (Platform.OS === 'web' ? 90 : 40),
    left: 20,
    zIndex: 999,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Dark translucent pill
    borderRadius: 20,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  cheerBubble: {
    position: 'absolute',
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 25,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  cheerText: {
    fontSize: 26,
  },
  dashboardContainer: {
    flex: 1,
    backgroundColor: '#111214', // Deep athletic dark grey
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
    paddingTop: 12,
    paddingBottom: 25,
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#2A2C31', // Subtle inner border for premium glass feel
  },
  dashboardCollapsed: {
    flex: 0,
    height: 180,
    justifyContent: 'flex-start',
  },
  dragHandleContainer: {
    width: '100%',
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dragHandle: {
    width: 48,
    height: 5,
    backgroundColor: '#3E4148',
    borderRadius: 2.5,
  },
  avatarHaloOuter: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 149, 0, 0.3)', // Tailing halo effect
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarHaloInner: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF9500',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#FF9500',
    overflow: 'hidden',
  },
  mapAvatarImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  mapAvatarEmoji: {
    fontSize: 18,
  },
  statsContainer: {
    paddingHorizontal: 40,
    paddingTop: 5,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statBox: {
    alignItems: 'center',
    flex: 1,
  },
  statValue: {
    fontSize: 42,
    fontWeight: '900',
    color: '#FFFFFF',
    fontVariant: ['tabular-nums'],
    letterSpacing: -1,
    // fontFamily: 'Barlow-Condensed',
  },
  statLabel: {
    fontSize: 11,
    color: '#8A8D93',
    marginTop: 6,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  friendsText: {
    textAlign: 'center',
    fontSize: 14,
    color: '#24C789',
    marginTop: 14,
    fontWeight: '600',
  },
  controlsContainer: {
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: Platform.OS === 'ios' ? 20 : 0,
  },
  preRunControls: {
    alignItems: 'center',
    width: '100%',
  },
  scopeSelectorContainer: {
    flexDirection: 'row',
    backgroundColor: '#1C1D21',
    borderRadius: 30,
    marginBottom: 24,
    padding: 5,
    width: '90%',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#2A2C31',
  },
  scopeBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 20,
    alignItems: 'center',
  },
  scopeBtnActive: {
    backgroundColor: '#2D2F36',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  scopeBtnText: {
    fontSize: 14,
    color: '#888',
    fontWeight: '600',
  },
  scopeBtnTextActive: {
    color: '#FFF',
    fontWeight: '800',
  },
  circleStartButton: {
    backgroundColor: '#E11D48', // Vibrant Rose from our UI System
    width: 96,
    height: 96,
    borderRadius: 48,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#E11D48',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 10,
    borderWidth: 4,
    borderColor: 'rgba(225, 29, 72, 0.3)',
  },
  circleStartText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  activeControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    paddingHorizontal: 20,
  },
  circlePauseButton: {
    backgroundColor: '#FF9500',
    width: 75,
    height: 75,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleResumeButton: {
    backgroundColor: '#E11D48',
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#E11D48',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  circleStopButton: {
    backgroundColor: '#1E1E1E',
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#333',
  },
  circleButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  cheerButton: {
    backgroundColor: '#F0F0F0',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: 'center',
    marginTop: 20,
  },
  cheerButtonText: {
    color: '#444',
    fontSize: 14,
    fontWeight: '600',
  },
  webMapOverlayCard: {
    position: 'absolute',
    top: Platform.OS === 'web' ? 20 : 40,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    zIndex: 10,
    alignItems: 'flex-end',
  },
  webMapOverlayText: {
    color: '#24C789',
    fontWeight: '800',
    fontSize: 14,
  },
  webMapOverlayCoords: {
    color: '#666',
    fontWeight: '600',
    fontSize: 12,
    marginTop: 2,
  },
});