import { StyleSheet, Dimensions, Platform } from 'react-native';

const { height } = Dimensions.get('window');

export default StyleSheet.create({
  recenterButton: {
    position: "absolute",
    right: 20,
    bottom: 220,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    overflow: 'hidden',
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 4,
  },
  container: {
    flex: 1,
    backgroundColor: '#F4F5F7',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F4F5F7',
  },
  loadingText: {
    fontSize: 16,
    color: '#888',
    fontWeight: '500',
  },
  mapContainer: {
    height: height,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : (Platform.OS === 'web' ? 90 : 40),
    left: 20,
    zIndex: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 20,
    overflow: 'hidden',
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  cheerBubble: {
    position: 'absolute',
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 25,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  cheerText: {
    fontSize: 26,
  },
  dashboardContainer: {
    position: 'absolute',
    bottom: -400,
    left: 0,
    right: 0,
    height: height * 0.75 + 400, // 3/4 screen expanded
    backgroundColor: 'rgba(255, 255, 255, 0.70)', overflow: 'hidden',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 8,
    paddingTop: 12,
    paddingBottom: 425,
    justifyContent: 'space-between',
  },
  dashboardCollapsed: {
    flex: 0,
    height: 180,
    justifyContent: 'flex-start',
  },
  dragHandleContainer: {
    width: '100%',
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dragHandle: {
    width: 48,
    height: 5,
    backgroundColor: '#E0E0E0',
    borderRadius: 2.5,
  },
  avatarHaloOuter: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(36, 199, 137, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarHaloInner: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#24C789',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#24C789',
    overflow: 'hidden',
  },
  mapAvatarImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  mapAvatarEmoji: {
    fontSize: 18,
  },
  statsContainer: {
    paddingHorizontal: 40,
    paddingTop: 5,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statBox: {
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 4,
  },
  statValue: {
    fontSize: 32,
    fontWeight: '900',
    fontFamily: Platform.OS === 'ios' ? 'HelveticaNeue-CondensedBlack' : 'sans-serif-condensed',
    color: '#222222',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0,
  },
  statLabel: {
    fontSize: 11,
    color: '#8A8A8A',
    marginTop: 6,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  friendsText: {
    textAlign: 'center',
    fontSize: 14,
    color: '#24C789',
    marginTop: 14,
    fontWeight: '600',
  },
  controlsContainer: {
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: Platform.OS === 'ios' ? 20 : 0,
  },
  preRunControls: {
    alignItems: 'center',
    width: '100%',
  },
  scopeSelectorContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(36, 199, 137, 0.1)',
    borderRadius: 30,
    marginBottom: 30,
    padding: 6,
    width: '85%',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(36, 199, 137, 0.2)',
  },
  scopeBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 24,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  scopeBtnActive: {
    backgroundColor: '#24C789',
    shadowColor: '#24C789',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  scopeBtnText: {
    fontSize: 14,
    color: '#24C789',
    fontWeight: '700',
  },
  scopeBtnTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  circleStartButton: {
    backgroundColor: '#24C789',
    width: 88,
    height: 88,
    borderRadius: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#24C789',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  circleStartText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  activeControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    paddingHorizontal: 20,
  },
  circlePauseButton: {
    backgroundColor: '#FF9500',
    width: 72,
    height: 72,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF9500',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  circleResumeButton: {
    backgroundColor: '#24C789',
    width: 72,
    height: 72,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#24C789',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  circleStopButton: {
    backgroundColor: '#FF453A',
    width: 72,
    height: 72,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF453A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  circleButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  cheerButton: {
    backgroundColor: '#F4F5F7',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: 'center',
    marginTop: 20,
  },
  cheerButtonText: {
    color: '#444',
    fontSize: 14,
    fontWeight: '600',
  },
  webMapOverlayCard: {
    position: 'absolute',
    top: Platform.OS === 'web' ? 20 : 40,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    zIndex: 10,
    alignItems: 'flex-end',
  },
  webMapOverlayText: {
    color: '#24C789',
    fontWeight: '800',
    fontSize: 14,
  },
  webMapOverlayCoords: {
    color: '#666',
    fontWeight: '600',
    fontSize: 12,
    marginTop: 2,
  },
});
